const texts = {
  splashName: 'TO DO CHALLENGE',
  emailPlaceholder: 'Seu@email.com',
  namePlaceholder: 'Seu nome',
  passwordPlaceholder: 'Sua senha',
  goToSignUp: 'Não tem login? Cadastre-se aqui',
  goToLogin: 'Já está cadastrado? Faça login',
  signUp: 'CADASTRAR',
  signUpTitle: 'Cadastre-se',
  emailInUse: 'Esse email já esta sendo usado',
  emailInvalid: 'Endereço de email inválido',
  writeEmail: 'Escreva seu email',
  writeName: 'Escreva seu nome',
  writePassword: 'Escreva sua senha',
  passwordTooShort: 'Senha muito curta',
  loginTitle: 'Faça login',
  login: 'Login',
  hello: 'Olá, ',
  myTasks: 'Minhas tarefas',
  newTask: 'Nova tarefa',
  createNewTask: 'Criar nova tarefa',
  taskName: 'Nome da tarefa',
  taskDate: 'Data da tarefa',
  startTime: 'Horário de início',
  endTime: 'Horário de término',
  description: 'Descrição',
  category: 'Categoria',
  categories: 'Categorias',
  createTask: 'Criar tarefa',
  sports: 'ESPORTES',
  health: 'SAÚDE',
  finances: 'FINANÇAS',
  fun: 'DIVERSÃO',
  educational: 'EDUCACIONAL',
  homework: 'TRABALHO CASEIRO',
  noNameError: 'Defina o nome da tarefa',
  at: ' as ',
  addCategoryBtn: '+',
  addCategory: 'Adicionar Categoria',
  newCategory: 'Nova categoria',
  addImage: 'Adicionar imagem',
  confirm: 'Confirmar',
};

export default texts;
